### ISSUE TITLE
synth: handle Iir_Kinds_Type_Attribute and Iir_Kinds_Scalar_Type_Attribute

### ISSUE THREAD

**Issue by Xiretza** [ghdl/ghdl#1098]
Just hit a `synth_expression_with_type: cannot handle IIR_KIND_HIGH_TYPE_ATTRIBUTE` and thought I'd open an issue to track it and the related attributes. Most aren't vitally important and can usually be worked around some other way, but are still nice to have.

**Comment by tgingold** [comment]
They are also easy to implement, feel free to post reproducers.
