### ISSUE TITLE
Documentation Details

### ISSUE THREAD

**Issue by sckoarn** [ghdl/ghdl#1150]
**Description**
Some of the command line options defined in the specification could be upgraded with examples and links back to the commands that use the options.

**Expected behaviour**
While using the GHDL users manual, it was found that the use of the -g option must be placed after the object being simulated in the run command line text.  The definition / description of -g option did not state or show where the option must be placed in the command line text.

It would be nice to have an example of usage for each option.  Some of the options have examples but -g does not.

Using the document, I tend to go to the option I need and just read there what the syntax is.  Since there was no example at that point,  I did not know I needed to place the -g option after the item being loaded.

**How to reproduce?**

**Context**
Please, provide the following information:

- OS:
- Origin:
 - https://readthedocs.org/projects/ghdl/downloads/pdf/latest/

```
******************** GHDL Bug occurred ***************************
Please report this bug on https://github.com/ghdl/ghdl/issues
...
******************************************************************
```

**Additional context**
Add any other context about the problem here. If applicable, add screenshots to help explain your problem.

**Comment by tgingold** [comment]
I have added an example for this option.
Do not hesitate to write your own patch (and submit a PR) to improve the doc.  It might even be less work than creating an issue!
