### ISSUE TITLE
GHDL installation

### ISSUE THREAD

**Issue by Trying2LearnLinux** [ghdl/ghdl#1151]
i have used the command line :

sudo apt-get install -y git make gnat zlib1g-dev

to install GHDL on my ubuntu Linux vivado system but i get an error every time i try it : 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
make is already the newest version (4.1-9.1ubuntu1).
zlib1g-dev is already the newest version (1:1.2.11.dfsg-0ubuntu2).
gnat is already the newest version (7ubuntu1).
git is already the newest version (1:2.17.1-1ubuntu0.5).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies.
 ghdl : Depends: libgnat-4.8 (>= 4.8.2-8ubuntu3) but it is not installable
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

this is the response i get when i type the command line, so i try the command line : 

 apt --fix-broken install

and this is the response i get : 

E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

am new to all of this and am trying to learn it so i can study and build state machines using ubuntu.

**Comment by eine** [comment]
@Trying2LearnLinux, I'm afraid that the issues you are finding are related to either your lack of knowledge of GNU/Linux systems, and/or an issue with the specific distribution and/or your hardware. Anyway, this has nothing to do with ghdl *per se*. I'd suggest to use more specific forums.

The solution to your permission error seems to be to add `sudo` before `apt --fix-broken install`.
