### ISSUE TITLE
synth: unhandled call to ieee function "floor"

### ISSUE THREAD

**Issue by bwimm** [ghdl/ghdl#1210]
**Description**
floor() does not seem to be implemented (ceil is)

```
library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.math_real.all;

entity bug is
  port (
    dummy   : in std_ulogic
  );
end entity;

architecture rtl of bug is
	constant a : real := floor(15.0/4.0);
	constant b : real := ceil(15.0/4.0);
begin
end architecture;
```

**Comment by tgingold** [comment]
Thanks for the issues.

**Comment by bwimm** [comment]
Thanks for the quick fixes.
Looks like ghdl is finally ok with my project (and produces ~140k lines of output 😅)
🎉
Time to run it through the testbenches

**Comment by tgingold** [comment]
Great!

The output is not particularly compact and its simulation is slow.
