### ISSUE TITLE
Race condition in `make ghdllib -j8`

### ISSUE THREAD

**Issue by forrestv** [ghdl/ghdl#1259]
Here's a cleaned-up build log I had where `make ghdllib -j8` failed (compiling the `v0.36` branch):

```
forrest@forrest-tool:~/ghdl/work/ghdl$ make ghdllib -j8
...
mkdir grt
...
cd grt; MSYS2_ARG_CONV_EXCL="-aI;-gnatec" gnatmake -u -c -g -gnatec/home/forrest/ghdl/work/ghdl/./src/grt/grt.adc -gnatdY -o main.o /home/forrest/ghdl/work/ghdl/./src/grt/main.adb -Igrt
/bin/sh: 1: cd: can't cd to grt
...
ar rcv lib/ghdl/libgrt.a `sed -e "/^-/d" -e "s!^!grt/!" < grt/grt-files` \
 jumps.o times.o grt-cbinding.o grt-cvpi.o fstapi.o lz4.o fastlz.o grt/run-bind.o grt/main.o
...
ar: grt/main.o: No such file or directory
src/grt/Makefile.inc:109: recipe for target 'lib/ghdl/libgrt.a' failed
make: *** [lib/ghdl/libgrt.a] Error 1
```

It seems that `mkdir grt` hadn't completed by the time that `cd grt` was attempted. Because `cd grt` is followed by a semicolon and not `&&`, the failure was ignored, and gnatmake dropped `main.o` into the wrong directory. Later on, `ar` couldn't find `main.o`.

The race condition exists because the `grt/main.o` target doesn't have `grt` (which runs `mkdir grt`) as a prerequisite, so `mkdir grt` runs in parallel with the `cd grt` command.

This still appears to be broken in the `master` branch (by inspection; I haven't been able to replicate this.)

Attached pull request #1260 fixes this.

**Comment by eine** [comment]
Does this have any relation with https://github.com/ghdl/ghdl/blob/master/Makefile.in#L607-L613?

**Comment by tgingold** [comment]
I don't think so.  It was only for grt.
