### ISSUE TITLE
GHW dumps not well tested

### ISSUE THREAD

**Issue by benreynwar** [ghdl/ghdl#1323]
Currently there are no tests that check that the generated ghw wave dumps are good.

I see two options to fix this:
1) Create some golden ghw dumps and confirm that the generated ghw dump matches.
2) Have some logic in the test that checks the content of the ghw file and points out exactly where the problem is.

Option (2) would clearly be more helpful for debugging, but option (1) would be much easier to implement.  I plan on starting off with (1) and only implementing (2) if it seems worth it.

**Comment by tgingold** [comment]
There is the ghwdump tool available in ghdl/src/grt which can dump a ghw file.  But it is not built.

You can start with a golden, and we will see how stable it is!
