### ISSUE TITLE
Wrong compilation order in compile-uvvm.sh script

### ISSUE THREAD

**Issue by mariuselv** [ghdl/ghdl#1344]
**Description**
Calling `compile-uvvm.sh -a` will fail due to wrong compilation order of UVVM VIPs

**Expected behaviour**
UVVM Utility Library and UVVM VVC Framework will compile, but compiling Bitvis VIP SBI will fail because the SBI VIP has Scoreboard VIP dependency. So, the bitvis_vip_scoreboard has to be moved to the beginning of the uvvm_vips list on line 60 in compile-uvvm.sh script.

**How to reproduce?**
Run: compile-uvvm.sh -a

**Comment by mariuselv** [comment]
There is a `script/component_list.txt` with the correct compile order which would better to utilize rather than hard coding the compile order in the compile-uvvm.sh script.

**Comment by tpcorrea** [comment]
GHDL has updated both shell and PowerShell script, so this issue on GHDL is fixed. Nevertheless, some VIPs fail to compile with GHDL.
