### ISSUE TITLE
libghdl (Python): Iterating nodes

### ISSUE THREAD

**Issue by Paebbels** [ghdl/ghdl#1551]
Why are design units iterated manually in a while loop, whereas ports are iterated in a for loop?

In the testcase [`units01/show_ports.py`](https://github.com/ghdl/ghdl/blob/master/testsuite/python/units01/show_ports.py?ts=2), two different iteration methods are used.  
Is there also an iterator available for design units (library units)?

```python
    unit = nodes.Get_First_Design_Unit(file)
    while unit != nodes.Null_Iir:
        lib_unit = nodes.Get_Library_Unit(unit)
        if nodes.Get_Kind(lib_unit) == nodes.Iir_Kind.Entity_Declaration:
            print("  - entity %s" % get_identifier_ptr(lib_unit))
            for port in pyutils.chain_iter(nodes.Get_Port_Chain(lib_unit)):

    # ...
    unit = nodes.Get_Chain(unit)
```

**Comment by tgingold** [comment]
I think iterators can be used on design units.
