### ISSUE TITLE
libghdl (Python): How to resolve names/references?

### ISSUE THREAD

**Issue by Paebbels** [ghdl/ghdl#1554]
Following the example/testcase in [`units01/show_ports.py`](https://github.com/ghdl/ghdl/blob/master/testsuite/python/units01/show_ports.py?ts=2#L92), an architectures entity name can be retrieved like this:

```python
entityNode = nodes.Get_Entity_Name(lib_unit)
entityName = name_table.Get_Name_Ptr(nodes.Get_Identifier(entityNode)).decode("utf-8")
```

While this is already OK for many usecases, I would like to resolve the entity name to the matching entity.  
I assume calling the parser like:  
```python
self.__ghdlFile =  sem_lib.Load_File(self.__ghdlSourceFileEntry)
```
is not enough to get this relationship. Especially, if entities and architectures are split across multiple files.

How to analyze or elaborate a design with `libghdl` to get these references?

**Comment by tgingold** [comment]
Load_File just load and parse the file.  If you want to load, parse and analyze you should use the python libghdl.analyze_file function.

(now in the right issue).
