### ISSUE TITLE
Provide (sub)commands for retrieving the git ref/hash

### ISSUE THREAD

**Issue by umarcor** [ghdl/ghdl#1577]
While packaging pyGHDL for MSYS2 (msys2/MINGW-packages#7569), a problem with dependencies arised. Python deps cannot be installed through `pip` in PKGBUILD recipes. At the same time, dependencies of pyGHDL (pydecor and pyVHDLModel) are not packaged for MSYS2. Hence, packaging pyGHDL would involve packaging those deps too, and probably other. After discussion with other MSYS2 contributors, I thought I'd step back from packaging pyGHDL.

The motivation for packing pyGHDL is to avoid mismatches between GHDL's AST and the bindings. We can partially solve it by tagging GHDL and releasing pyGHDL to pip frequently. However, potentially all commits can be tagged, so that would mean doing continuous delivery. I don't think that's realistic.

Users can use `ghdl version` for checking the git ref/hash that corresponds to the GHDL binary. Then, they can checkout the version of the git repo and install from there. Or they can use `pip install git+https://github.com/ghdl/ghdl.git@REF`. Yet, parsing the output of `ghdl version` is not trivial. In practice, it's easier to do it manually than attempting to automate it.

Therefore, this is a feature request for `ghdl version ref` and/or `ghdl version sha` to be added. `sha` would always return the commit SHA. `ref` would return the tag name or the SHA, if that's a non-tagged commit. Other syntaxes might be used, e.g. `ghdl --version-ref`, `ghdl version --ref`, `ghdl --version --ref`... The purpose is for users to get matching Python bindings through:

```
pip install git+https://github.com/ghdl/ghdl.git@$(ghdl version sha)
```

**Comment by Paebbels** [comment]
I would recommend:
* `ghdl version` to report the normal version test. Long term a replacement for `ghdl --version`.
* `ghdl version --ref` a flavor of version to report only the reference (tag or branch) in a machine readable form, maybe without final line break to ease handling in `$()` expressions.
* `ghdl version --sha` or `ghdl version --hash`, like `--ref` but for a (full) hash.  
  Alternatives:
  * `--hash` reports an 8-chat hash,
  * `--sha` the 40-char hash.
