### ISSUE TITLE
[1.0.0] No bash shebang line in scripts/vendors/config.sh

### ISSUE THREAD

**Issue by yurivict** [ghdl/ghdl#1626]
**Description**
https://github.com/ghdl/ghdl/blob/master/scripts/vendors/config.sh doesn't have the "bash" interpreter shebang line, which would cause it to break when the current shell is not bash.

**Comment by tgingold** [comment]
I am not sure to understand why is it a problem.  This file is sourced from the other script files like compile-xilinx-ise.sh which uses the bash shell.

**Comment by yurivict** [comment]
Ok, thanks, then this isn't a problem.
