### ISSUE TITLE
Some vendor library files fail to compile using PoSh scripts

### ISSUE THREAD

**Issue by SalttownUser** [ghdl/ghdl#1975]
**Description**
When compiling vendor libraries on Windows using `compile-<vendor>.ps1`scripts on an actual nightly build asset `MINGW32-mcode-standalone.zip` some vendor library files fail to compile due to a buggy function call leading to this error message:

~~~powershell
Compiling library 'cycloneiv' ...
Start-PackageCompilation: <somepath>\MINGW32-mcode-standalone\lib\ghdl\vendors\compile-intel.ps1:436:56
Line |
 436 |  … rorCount += Start-PackageCompilation $GHDLBinary $GHDLOptions $Destin …
     |                                                     ~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Analyze_Parameters' because it is null.

Start-PackageCompilation:<somepath>\MINGW32-mcode-standalone\lib\ghdl\vendors\compile-intel.ps1:451:56
Line |
 451 |  … rorCount += Start-PackageCompilation $GHDLBinary $GHDLOptions $Destin …
     |                                                     ~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Analyze_Parameters' because it is null.

...
~~~

The script fails to call the function [`Start-PackageCompilation`](https://github.com/ghdl/ghdl/blob/778ee5cbb8f7a936f8d4cc93ec6b4671bec2008e/scripts/vendors/shared.psm1#L241).\
The error appears for some Intel/Altera as well as for some Lattice devices.

The function is used for every device. When working, the second parameter is `$Analyze_Parameters`. When failing, the second parameter is `GHDLOptions`. `GHDLOptions` is not defined anywhere but is the [name for the parameter inside the function](https://github.com/ghdl/ghdl/blob/778ee5cbb8f7a936f8d4cc93ec6b4671bec2008e/scripts/vendors/shared.psm1#L251).

Actual code and fix:

~~~diff
	if (Test-Path $SourceFiles[0])
-	{	$ErrorCount += Start-PackageCompilation $GHDLBinary $GHDLOptions $DestinationDirectory $Library
+	{	$ErrorCount += Start-PackageCompilation $GHDLBinary $Analyze_Parameters $DestinationDirectory $Library 
$VHDLVersion $SourceFiles $SuppressWarnings $HaltOnError -Verbose:$EnableVerbose -Debug:$EnableDebug
		$StopCompiling = $HaltOnError -and ($ErrorCount -ne 0)
	}
~~~

**Expected behaviour**
Compile all Lattice and Intel library files without error message.

**How to reproduce?**
Example using PowerShell:
1. Navigate to `<local path>\MINGW32-mcode-standalone\lib\ghdl\vendors`
2. Run `.\compile-intel.ps1  -All`
3. Run `.\compile-lattice.ps1  -All`
   
**Context**
Please, provide the following information:

- OS: Windows 10
- Origin:
  - Released binaries: `[MINGW32-mcode-standalone.zip](https://github.com/ghdl/ghdl/releases/download/nightly/MINGW32-mcode-standalone.zip)`
- Lattice Diamond 3.12
- Intell Quartus 20.1

**Comment by Paebbels** [comment]
Looks like these wrong parameter names are only present in the FPGA chip families that I couldn't check on my local installations. Anyhow, when reworking the script, a clean search and replace by me should have covered it. Argh.

Thanks for proposing a fix and also for testing with a full version.
