### ISSUE TITLE
doc link redirects to online casino

### ISSUE THREAD

**Issue by matsievskiysv** [ghdl/ghdl#2068]
["Yosys Open Synthesis Suite"](http://www.clifford.at/yosys/) link at [documentation page](https://ghdl.github.io/ghdl/using/Synthesis.html#yosys-plugin) redirects to some online casino.

**Comment by Paebbels** [comment]
There is
* https://yosyshq.net/ and
* https://yosyshq.net/yosys/

I suspect the latter is the intended target, right?

**Comment by matsievskiysv** [comment]
> I suspect the latter is the intended target, right?

@Paebbels looks like it.
