### ISSUE TITLE
Exponentiation and unary minus

### ISSUE THREAD

**Issue by bjourne** [ghdl/ghdl#2189]
The output of this code is 512:
```
library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;
use work.all;

entity bug02 is
end bug02;

architecture rtl of bug02 is
    FUNCTION weird (bw : integer range 2 to 32)
        RETURN INTEGER IS
    BEGIN
        RETURN -(2**(bw - 1));
    END weird;
begin
    process
    begin
        report to_string(weird(10));
        wait;
    end process;
end architecture;
```
In modelsim the output is -512. Maybe GHDL knows something I  don't, but it really seems to me that the output should be -512 here? If I change the function to `RETURN -1 * (2**(bw - 1));` I get what I think is the right output in GHDL too.

GHDL 3.0.0-dev (2.0.0.r581.gcb3e7b0f9) [Dunoon edition]
 Compiled with GNAT Version: 12.2.0
 mcode code generator

**Comment by tgingold** [comment]
Ok, I think it works correctly with gcc or llvm backends.  I am investigating.
