### ISSUE TITLE
Gate Delay in Simulation

### ISSUE THREAD

**Issue by jjjt-git** [ghdl/ghdl#2280]
When running a testbench of a concurrent section, it would be nice to allow specifying a per-gate delay in simulation, so it would be easier to debug timing issues in a design.

My idea for this would be a command line option while running, which applies the specified delay for the specified operation.

**Comment by tgingold** [comment]
That's what SDF is for!

**Comment by jjjt-git** [comment]
Ok, thanks. I must have overlooked this.
