### ISSUE TITLE
Uninstall leaves files on disk

### ISSUE THREAD

**Issue by Paebbels** [ghdl/ghdl#2316]
**Description**

When calling `make uninstall`, some files remain on disk.

* `include/ghdl/synth.h`
* `include/ghdl/synth_gates.h`
* `libghdl.a`
* `libghdl.link`
* `libghw.dll`

**Expected behaviour**

As many files of GHDL are removed from disk, I suspect these files should get deleted too. Especially as these files are "new" to GHDL ;). I assume an oversight when adding rules to the `Makefile.in`.

**How to reproduce?**

Tested with MSYS2/MinGW32 mcode.

```
mkdir -p build/ming32-mcode
cd build/ming32-mcode
../../configure --prefix=/c/Tools/ghdl/3.0.0.dev0-mingw32-mcode
make
make install
make uninstall
```

**Additional context**

Output of `PS> dir | tree /f`
```
├───bin
├───include
│   └───ghdl
│           synth.h
│           synth_gates.h
│
└───lib
        libghdl.a
        libghdl.link
        libghw.dll
```

**Comment by OmarElfouly** [comment]
Hello @Paebbels 

I'm new to contributing and I'm excited to get started on this issue :)

I just wanted to confirm that the expected behavior is to remove the files that were listed and that the recommended starting point is MakeFile.in

**Comment by Paebbels** [comment]
I'm currently reworking the GHDL pipeline, maybe such a check should be part of the pipeline.

**Comment by OmarElfouly** [comment]
Sounds like a great idea.
Also I'll make a start on going through the MakeFile :)

**Comment by OmarElfouly** [comment]
I panicked for a bit when i saw the build check fail but it looks like that's an issue that exists on master. Is that right @Paebbels

**Comment by Paebbels** [comment]
To which pipeline are you referring? Can you post a pipeline link?

I activated the pipeline for your PR. It's currently running.
