### ISSUE TITLE
GHDL with LLVM backend doesn't work standalone anymore

### ISSUE THREAD

**Issue by Paebbels** [ghdl/ghdl#2318]
This is a followup on #1560, #2314 and #2315.

**Description**

GHDL compiled with MinGW64 (or UCRT64) using LLVM backend, can't be used standalone anymore.  
So far I have identified 2 problems:
1. When providing `gcc.exe` along side to `ghdl.exe`, it's not detected anymore.  
   > C:\Tools\GHDL\3.0.0.dev0-mingw64-llvm\bin\ghdl.exe: installation problem: cc not found
2. When analyzing and elaborating a simple design `e` from within MSYS2/MinGW64 environment, an `e.exe` is generated. This executable requires now `zlib1.dll` t be in the same directory as `e.exe`.  
   In previous versions of GHDL-llvm, `zlib1.a` was statically linked into the elaborated design.

**Note:**

    This behavior was checked by me for longer time, as `libghdl` and `pyGHDL` doesn't have these
    requirements. In addition, simulation on Windows is using the standalone MinGW32 mcode variant,
    so standalone MinGW64 llvm was used for longer time.

**Expected behaviour**

GHDL with LLVM backend compiled with MinGW64 (or UCRT64) should be usable as standalone installation as before.

**How to reproduce?**

#2314 and #2315 can be used to reproduce. It also contains LLVM rules.

**Additional context**

Maybe when it's possible to install GHDL in standalone mode via `make install` and get it regularly checked via GitHub Actions.

**Comment by tgingold** [comment]
Let's close this as unsupported.
