### ISSUE TITLE
How to set simulation time precision?

### ISSUE THREAD

**Issue by r2com** [ghdl/ghdl#2415]
I am using now GHDL and when I run it I run together with VPI C program. Default I see precision is 1fs, how do i change it for example to 1ps?

i saw some flags shown for the ghdl run command, but current revision of ghdl does not recognize them

**Comment by tgingold** [comment]
If you use the mcode back-end, you can use --time-resolution=ps

**Comment by umarcor** [comment]
Refs: #1281, #1769

**Comment by r2com** [comment]
need to reopen issue.

I am using gcc backend (because I want to use gcov), in that case, how would I change precision?

**Comment by umarcor** [comment]
As explained in #1281, it's not possible.
