### ISSUE TITLE
libghw: handling large ghw files (performance)

### ISSUE THREAD

**Issue by soenke-brandt** [ghdl/ghdl#2548]
**Description**
Use of libghw in gtkwave leads to long loadtimes when working with large ghw files.

**Expected behaviour**
Loadtime in the range of seconds (instead of minutes).

**How to reproduce?**
A suitable workload is linked here in [this specific comment in gtkwave #280](https://github.com/gtkwave/gtkwave/issues/280#issuecomment-1791391127)

**Additional context**
For discussion and analysis in a gtkwave context, see [gtkwave #280](https://github.com/gtkwave/gtkwave/issues/280) and this [Issue](https://gitlab.fel.cvut.cz/canbus/ctucanfd_ip_core/-/issues/284) and [Patch](https://gitlab.com/canfd/server-tools/-/commit/7d0e8b6d01b3406b8167f7fcbf44f4e714e7c7cf) from another project.

**Comment by tgingold** [comment]
If you are using the mcode backend, you'd better to use the fst dumper.

I will have a look at the patch too.

**Comment by tgingold** [comment]
@stefanlippuner I think the patch should also be applied for gtkwave/gtkwave#280, correct ?

**Comment by stefanlippuner** [comment]
> @stefanlippuner I think the patch should also be applied for [gtkwave/gtkwave#280](https://github.com/gtkwave/gtkwave/issues/280), correct ?

Yes, I'll also open a PR there.
