### ISSUE TITLE
$CC -dumpmachine vs. config.guess?

### ISSUE THREAD

**Issue by ams** [ghdl/ghdl#2583]
I think it would be preferable to use config.guess to figure out ./configure to figure out the $build variable -- the reason is that config.guess is specifically designed for the task, and is what is normally used to figure out the build machine, and a unique enough identifier.

Right now "$CC -dumpmachine" and ./config.guess report different things:

```
~/ghdl $ gcc -dumpmachine
arm64-apple-darwin23.3.0
~/ghdl $ ~/emacs/build-aux/config.guess 
aarch64-apple-darwin23.3.0
```

It is mostly cosmetic I suppose ... but a patch to add config.guess and use that be of interest?

**Comment by tgingold** [comment]
I am not sure which issue you try to address.  We don't need to support many architecture/OS.  And config.guess also needs to be maintained (at least updated).
