### ISSUE TITLE
GHDL 2.9.1 binary for windows overwrites path entirely

### ISSUE THREAD

**Issue by Kanken6174** [ghdl/ghdl#2653]
**Description**
This specific version of GHDL's installer will remove any other data in the os's PATH variable, breaking a ton of programs, this shouldn't happen.

**Expected behaviour**
The installer should append its path to the windows path environnement variable, not overwrite it.

**How to reproduce?**
Install ghdl 2.9.1 from this link and let it replace the path:
[installer 2.9.1](http://ghdl.free.fr/ghdl-installer-0.29.1.exe)

**Context**
Please, provide the following information:

- OS: windows 11 23H2
- Origin:
  - [ ] Package manager: `version`
  - [x] Released binaries: `tarball_url`
  - [ ] Built from sources: `commit SHA`

**Comment by tgingold** [comment]
Version 0.29.1 is very very old.  Get the latest versions from github.
