### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Alaa-Elshahawy** [ghdl/ghdl#2655]
no idea why this occure, also i can't find the  trans.adb where the line 553 is causing the bug, if i understand it correctly.

******************** GHDL Bug occurred ***************************
Please report this bug on https://github.com/ghdl/ghdl/issues
GHDL release: 1.0.0 (Ubuntu 1.0.0+dfsg-6) [Dunoon edition]
Compiled with GNAT Version: 10.3.1 20211117
Target: x86_64-linux-gnu
/home/alaa/dvb_fpga/
Command line:
/usr/bin/ghdl-mcode --elab-run --std=08 --work=lib --workdir=/home/alaa/dvb_fpga/vunit_out/ghdl/libraries/lib -P/home/alaa/dvb_fpga/vunit_out/ghdl/libraries/vunit_lib -P/home/alaa/dvb_fpga/vunit_out/ghdl/libraries/osvvm -P/home/alaa/dvb_fpga/vunit_out/ghdl/libraries/lib -P/home/alaa/dvb_fpga/vunit_out/ghdl/libraries/str_format -P/home/alaa/dvb_fpga/vunit_out/ghdl/libraries/fpga_cores -P/home/alaa/dvb_fpga/vunit_out/ghdl/libraries/fpga_cores_sim -frelaxed-rules dvbs2_encoder_tb dvbs2_encoder_tb -gtest_cfg=MOD_QPSK,FECFRAME_SHORT,C1_4,False,/home/alaa/dvb_fpga/gnuradio_data/FECFRAME_SHORT_MOD_QPSK_C1_4|MOD_32APSK,FECFRAME_SHORT,C3_4,False,/home/alaa/dvb_fpga/gnuradio_data/FECFRAME_SHORT_MOD_32APSK_C3_4|MOD_QPSK,FECFRAME_NORMAL,C5_6,False,/home/alaa/dvb_fpga/gnuradio_data/FECFRAME_NORMAL_MOD_QPSK_C5_6|MOD_8PSK,FECFRAME_SHORT,C3_5,False,/home/alaa/dvb_fpga/gnuradio_data/FECFRAME_SHORT_MOD_8PSK_C3_5|MOD_QPSK,FECFRAME_NORMAL,C1_2,False,/home/alaa/dvb_fpga/gnuradio_data/FECFRAME_NORMAL_MOD_QPSK_C1_2|MOD_32APSK,FECFRAME_SHORT,C4_5,False,/home/alaa/dvb_fpga/gnuradio_data/FECFRAME_SHORT_MOD_32APSK_C4_5|MOD_8PSK,FECFRAME_NORMAL,C3_4,False,/home/alaa/dvb_fpga/gnuradio_data/FECFRAME_NORMAL_MOD_8PSK_C3_4|MOD_QPSK,FECFRAME_SHORT,C8_9,True,/home/alaa/dvb_fpga/gnuradio_data/FECFRAME_SHORT_MOD_QPSK_C8_9 -gnumber_of_test_frames=1 -gseed=-1237806400 -grunner_cfg=active python runner : true,enabled_test_cases : back_to_back,output path : /home/alaa/dvb_fpga/vunit_out/test_output/lib.dvbs2_encoder_tb.test_all_configs.back_to_back_5905a78c6ddca5f76b6b50b613e680a68e38c0b5/,tb path : /home/alaa/dvb_fpga/testbench/,use_color : true --assert-level=error --ieee-asserts=disable
Exception TYPES.INTERNAL_ERROR raised
Exception information:
raised TYPES.INTERNAL_ERROR : trans.adb:553
Call stack traceback locations:
0x559c6e55913d 0x559c6e55951b 0x559c6e559797 0x559c6e6eefc8 0x559c6e6ffe5a 0x559c6e75c038 0x559c6e733730 0x559c6e733a0f 0x559c6e73381c 0x559c6e77ba78 0x559c6e77bb9f 0x559c6e77c1f8 0x559c6e77c98a 0x559c6e77e596 0x559c6e77e6eb 0x559c6e781b0f 0x559c6e7863f8 0x559c6e7864c6 0x559c6e74a4fa 0x559c6e73deac 0x559c6e74ed8c 0x559c6e7490a0 0x559c6e78eb55 0x559c6e6cd250 0x559c6e60569e 0x559c6e7924b3 0x559c6e3bdb07 0x7f0f611d4d8e 0x7f0f611d4e3e 0x559c6e3bc243 0xfffffffffffffffe

**Comment by Paebbels** [comment]
Version v1.0.0 is very old. Dozens of features were added and hundreds of bugs have been fixes over the time.

Please update to v4.1 (or compile from sources for v5.0.0-dev).
