### ISSUE TITLE
What happened to nightly's Linux versions?

### ISSUE THREAD

**Issue by stnolting** [ghdl/ghdl#2664]
Hey there!

I am using the [setup-ghdl](https://github.com/marketplace/actions/setup-ghdl) GitHub action to install a Linux version of GHDL, but it seems these are missing now in the nightly release. Is this on purpose? Or maybe I am missing something? 🤔

![grafik](https://github.com/ghdl/ghdl/assets/22944758/aa3ee030-9905-4c2a-8073-5c4695322629)

![grafik](https://github.com/ghdl/ghdl/assets/22944758/1b724427-0e7c-40c9-bbca-f1a7572f30bd)

**Comment by LukasVik** [comment]
@tgingold Works perfectly for me now. Thank you!

**Comment by tgingold** [comment]
Great.  Sorry for the breakage.

**Comment by stnolting** [comment]
Works again on my side, too! Thank you so much for the quick fix!
