### ISSUE TITLE
build error: netlists-iterators.ads:25:06: aspect identifier expected

### ISSUE THREAD

**Issue by dsula** [ghdl/ghdl#2671]
I'm having trouble building ghdl from source with several error messages

```
netlists-iterators.ads:25:06: aspect identifier expected
netlists-iterators.ads:28:46: aspect identifier expected
netlists-iterators.ads:46:06: aspect identifier expected
```
I have no idea about Ada. Could anybody point me in the right direction? What could be wrong with my setup?

centos 7
gcc-gnat 4.8.5

**Comment by maehne** [comment]
Please, check the [build instructions](https://ghdl.github.io/ghdl/development/building/index.html). GHDL requires at least GCC 8.1. So CentOS 7's GCC version is simply too old. You may try to turn of synthesis support, to see if it suffices to make a build succeed.

**Comment by dsula** [comment]
Ok, thank you. Need to upgrade then.
