### ISSUE TITLE
gnat compiler in `adacore` is no longer available

### ISSUE THREAD

**Issue by wieniawski-lai** [ghdl/ghdl#2730]
**Description**
In [GHDL official site](https://ghdl.github.io/ghdl/development/building/index.html#build) building guide, it is said that ada compiler is used, where `http://libre.adacore.com/tools/gnat-gpl-edition/` is advised.

However `http://libre.adacore.com/tools/gnat-gpl-edition/` is no longer exist.

So where can I found a new `gnat compiler`?

**Comment by Paebbels** [comment]
For a few year, GHDL is compiled for Windows using MSYS2 with MinGW32, MinGW64 and UCRT64 environments. Also for MinGW32, `gcc-ada` was discontinued. You can either download precompiled GHDLs from GitHub Action pipelines, install GHDL in MSYS2 via pacman or compile it yourself using gcc in MSYS2 UCRT64.

-----
Of cause, we need to update these instructions and adjust to the changed reality for GNAT.
