### ISSUE TITLE
Support running multiple units/combining multiple waveform files into one

### ISSUE THREAD

**Issue by DUOLabs333** [ghdl/ghdl#2787]
**Is your feature request related to a problem? Please describe.**
I have a file where multiple entities have each have their own testbench, and I want to test them all at once. However, currently, you can only run a single entity in an invocation.

**Describe the solution you'd like**
It would be nice if `elab-run`/`run` could run multiple units at a time.

**Describe alternatives you've considered**
Alternatively, I could run each testbench separately, have each run save its waveform to a different file, and then combine all of the waveforms into one file, where run i+1 would immediately succeed run i in the new file.

**Additional context**
N/A

**Comment by Paebbels** [comment]
the requested feature is not directly the duty of a simulator and/or compiler. You're requesting a test execution framework. Have a look at [VUnit](https://github.com/VUnit/vunit) or [OSVVM](https://github.com/OSVVM/OSVVM-Scripts). Both offer such features. There are others available too.

**Comment by tgingold** [comment]
The simplest is to create a wrapper that instantiate all the units you want to test.

**Comment by DUOLabs333** [comment]
@tgingold I worked around this by just creating a wrapper. Thanks for the suggestion.
