### ISSUE TITLE
gen-makefile not behaving entirely correct

### ISSUE THREAD

**Issue by faf5678** [ghdl/ghdl#624]
when i give an option such as -fexplicit to the ghdl --gen-makefile command, because it is necessary then it will also always be necessary for ghdl invocations in the Makefile, no? Shouldn't it just always be included in GHDLFLAGS? I end up regularly fixing a generated Makefile this way.

**Comment by tgingold** [comment]
Make sense.  I have added -fXXX and --std=

Thank you for the report.
