### ISSUE TITLE
UVVM compilation fails

### ISSUE THREAD

**Issue by xmentos** [ghdl/ghdl#658]
While trying to compile the latest github UVVM libraries the compilation failed, which was easily fixed by checking the compile_order.txt files in their repo. Attached a patch that fixes this, together with a documentation typo. What is the preferred way of sending patches BTW?
[ghdl-pvt1.log](https://github.com/ghdl/ghdl/files/2390582/ghdl-pvt1.log)

**Comment by 1138-4EB** [comment]
https://ghdl.readthedocs.io/en/latest/contribute.html#fork-modify-and-pull-request

**Comment by tgingold** [comment]
It took me a long time, but I have merged the patch.

Thanks!
