### ISSUE TITLE
access violation exception

### ISSUE THREAD

**Issue by Ravenwater** [ghdl/ghdl#664]
**Description**
Receiving an access violation exception during simulation

**Expected behaviour**
if there is a user type definition error, some guidance what is causing the crash

**Context**
******************** GHDL Bug occurred ***************************
Please report this bug on https://github.com/ghdl/ghdl/issues
GHDL release: @VER@ (tarball) [Dunoon edition]
Compiled with GNAT Version: GPL 2017 (20170515-63)
Target: i686-pc-mingw32
In directory: C:\Users\tomtz\Documents\dev\clones\posit-data-path-generator\test\
Command line:
C:\eda\ghdl\bin\ghdl.exe -r --std=08 quire_accumulator_tb behavior --wave=quire_accumulator.ghw
Exception PROGRAM_ERROR raised
Exception information:
raised PROGRAM_ERROR : EXCEPTION_ACCESS_VIOLATION
******************************************************************

- OS: Win10
- Origin:
  - [ ] Package manager. Repo:
  - [ x] Released binaries. Tarball: ghdl-mcode-0.36-dev
  - [ ] Built from sources. Commit SHA:

**Additional context**
N/A

**How to reproduce?**
test program

**Files**
[mre.zip](https://github.com/ghdl/ghdl/files/2432019/mre.zip)

**Comment by Paebbels** [comment]
Has this test been done with the GHDL version provided in #656?

**Comment by Ravenwater** [comment]
@Paebbels  yep, using that 0.36-dev version from #656

**Comment by tgingold** [comment]
Was fixed.

**Comment by Ravenwater** [comment]
where can I find the ghdl with the fix?

**Comment by tgingold** [comment]
You need to build from sources.
