### ISSUE TITLE
Warning is unclear how to resolve

### ISSUE THREAD

**Issue by Ravenwater** [ghdl/ghdl#671]
**Description**
My code generates a warning, but the message reported does not provide information how to resolve the issue that is causing the warning.

**Expected behaviour**
information that helps me resolve the cause

**Context**
warning: can't assert that process labeled "combinational" has not wait; will be checked at elaboration [-Wdelayed-checks]

Question: Assuming that the english grammar mistake "has not wait" was intended to read "has no wait", it would be nice to know how to resolve it. None of the code in the module that reports the warning contains any waits or asserts.

**Comment by tgingold** [comment]
Yes, there is a grammar mistake.

The warning just tell you an error may be reported at elaboration (when it has a full view of the design).
Just suppress the warning (-Wno-delayed-checks) if it is annoying.
