### ISSUE TITLE
PowerShell installation fail on Windows 10 (x64) [1803]

### ISSUE THREAD

**Issue by dotSK** [ghdl/ghdl#678]
**Description**
Installation fails because of Expand-Archive function. In linked issue, it seems that the PCSX provided function of the same name confilcts with builtin one. PowerShell reports that it doesn't know options '-OutputPath' and '-ShowProgress'. Furthermore, because it expects a zip file, a file with .tmp extension is not recognized.

**Expected behaviour**
To successfully install GHDL using PowerShell.

EDIT:
I see, that some people were having the same problem in the past. So should the script be changed or is the solution still to install/depend on PCSX?

[linked issue](https://github.com/ghdl/ghdl/issues/457)

**Comment by dotSK** [comment]
I have the pull request ready fixing this, assuming we choose to go "builtin function" way.

**Comment by Paebbels** [comment]
Of cause, you can create a PR. I'll do a review and afterwards merge your proposed changes.

PowerShell incorporated a lot of functionally, that was missing some versions ago. So PSCX was needed to get a good working PS environment.

The idea is:
- Who wants to install GHDL with the PS package/scripts should not need PSCX.
- Who likes to compile GHDL might still need PSCX for e.g. packaging.

**Comment by 1138-4EB** [comment]
@dotSK, just a suggestion: you can use `#457` instead of `[linked issue](https://github.com/ghdl/ghdl/issues/457)` to cross-reference issues in this same repo. Furthermore, you can use `user/repo#000` to reference issues in other github projects.
