### ISSUE TITLE
Document -g<generic>=<value> option

### ISSUE THREAD

**Issue by cmarqu** [ghdl/ghdl#686]
https://github.com/ghdl/ghdl/blob/master/doc/using/Simulation.rst says 
> In GHDL, it is impossible to pass parameters to your design. A later version could do it through the generic interfaces of the top entity.

With the ``-g<generic>=<value>`` option (https://sourceforge.net/p/ghdl-updates/tickets/37/), this appears obsolete.

**Comment by 1138-4EB** [comment]
Indeed, see #608.

**Comment by cmarqu** [comment]
Closing as duplicate.
