### ISSUE TITLE
New git tag

### ISSUE THREAD

**Issue by m3tav3rse** [ghdl/ghdl#712]
Could you tag a new release?

**Comment by 1138-4EB** [comment]
I asked about it just a couple of days ago: https://github.com/ghdl/ghdl/issues/702#issuecomment-441662648

**Comment by m3tav3rse** [comment]
Sorry, I missed that

**Comment by 1138-4EB** [comment]
@m3tav3rse no need to apologise. My comment in #702 was off-topic, so it is completely reasonable that you skipped it. I added it just as a reference.

BTW, a new release was tagged today: https://github.com/ghdl/ghdl/releases However, binaries for windows are not ready yet.
