### ISSUE TITLE
List all warning that are enabled by default

### ISSUE THREAD

**Issue by Paebbels** [ghdl/ghdl#728]
I was searching the documentation on how to disable the `-Whide` warning. I noticed, that there is no list of warning, which are enabled by default.

Please add this list to the section about warnings: https://ghdl.readthedocs.io/en/latest/using/InvokingGHDL.html?highlight=disable#warnings

This is what I figured out so far:
* `-Whide`
* `-Wothers`
* `-Wparenthesis`
* `-Wshared`
* `-Wbody`
* `-Wstatic`
* `-Wlibrary`
* `-Wpure`

Is there a different set of warnings enabled, when GHDL runs in verbose mode (`-v`)?

**Comment by Paebbels** [comment]
@tgingold accordig to what I figured out while running the pre-compile scripts, the warnings

- `Wothers`
- `Wparenthesis`
- `Wbody`
- `Wstatic`

are also enabled, but not listed in your commit 0105520.

**Comment by tgingold** [comment]
All warnings were enabled before.
