### ISSUE TITLE
Adding libraries to the vendors directory.

### ISSUE THREAD

**Issue by m-kru** [ghdl/ghdl#775]
Is it desirable to add libraries,  that are not vendor libraries or popular libraries (like OSVVM or UVVM) to the vendors directory? 

Namely, I work with the [IPbus](https://github.com/ipbus/ipbus-firmware) and I need to create a library for myself anyway. I thought, that by the way, I could add it to the ghdl and prepare some compile scripts.

**Comment by tgingold** [comment]
I am OK with adding building scripts in vendors, but another possibility is to add scripts in IPbus.  That looks better for maintainability.

**Comment by m-kru** [comment]
Ok, I will make PR to the IPbus with hope that it will be accepted.

**Comment by tgingold** [comment]
Another possibility is to describe IPbus using FuseSoc, so that it could be compiled on all analyzers supported by FuseSoc.
