### ISSUE TITLE
[question] are records supported by VCD?

### ISSUE THREAD

**Issue by arcturus140** [ghdl/ghdl#783]
my record is of type `std_logic_vector`:

```
type tCONST is record
   A : std_logic_vector(3 downto 0);
end record;
signal constrB : tCONST;
```

My VCD tells me that it is not handled:

```
$comment constrb is not handled $end
```

Can GHDL dump records into VCD's?

**Comment by tgingold** [comment]
The quick answer is no: records aren't dumped in VCDs.
