### ISSUE TITLE
Option to Remove "NUMERIC_STD.TO_INTEGER: metavalue detected, returning 0"

### ISSUE THREAD

**Issue by Bamban** [ghdl/ghdl#790]
Hello,

I have a simulation with a lot of them... I have found reference of an option here: https://sourceforge.net/p/ghdl-updates/tickets/106/
But it is nowhere to be found in the current version of the docs! Is this still working?

**Comment by 1138-4EB** [comment]
Hi @Bamban! That's documented here: https://ghdl.readthedocs.io/en/latest/using/Simulation.html#cmdoption-ghdl-assert-level. For the specific warning you mention, you might want to use `--ieee-asserts`: https://ghdl.readthedocs.io/en/latest/using/Simulation.html#cmdoption-ghdl-ieee-asserts.

**Comment by Bamban** [comment]
My bad, I haven't looked closely enough!
Thanks for the pointer.
