### ISSUE TITLE
[question] purpose of --link flag

### ISSUE THREAD

**Issue by arcturus140** [ghdl/ghdl#823]
ghdl help lists a link flag: 

    --link [OPTS] UNIT [ARCH]  Link UNIT

I overlooked this option in the documentation. What is the purpose and usage for this option? Is it similar to `list-link`?

**Comment by 1138-4EB** [comment]
It is provided only for completeness: https://ghdl.readthedocs.io/en/latest/references/CommandReference.html#link-link

After you have analyzed the sources with `ghdl -a` you can:

- `ghdl -e`
- `ghdl --bind` + `ghdl --list-link` + `ghdl --link`
- `ghdl --bind` + `ghdl --list-link` + `ghdl -e`
- `ghdl --bind` + `ghdl --list-link` + `gcc`

**Comment by tgingold** [comment]
Note that `ghdl --list-link` does not create any file, it just dumps the files to be linked.

`ghdl -e` is equivalent to `ghdl --bind` followed by `ghdl --link`.

**Comment by 1138-4EB** [comment]
> Note that `ghdl --list-link` does not create any file, it just dumps the files to be linked. `ghdl -e` is equivalent to `ghdl --bind` followed by `ghdl --link`.

I misclicked and sent the first message after C&P some lines but before cleaning them. I hope it is correct now.
