### ISSUE TITLE
Add tests in the CI matrix for internal Makefiles

### ISSUE THREAD

**Issue by eine** [ghdl/ghdl#847]
As commented in #846, currently some of the internal makefiles are not tested in the CI jobs:

> [@tgingold]
> The files created are checked in so that the build is (slightly ?) easier. Maybe > we could call the makefile (and check for no-change) in one builder.

We should consider adding a builder/job to the matrix, as @tgingold suggested. Alternatively, we can evaluate the added complexity of removing the files which can be generated with a few additional `make` executions. Moreover, these executions can be added to the main Makefile, so the build procedure does not change: https://www.gnu.org/software/make/manual/html_node/Recursion.html

**Comment by tgingold** [comment]
Generated files are now checked for being up to date.
