### ISSUE TITLE
Update NEWS.md

### ISSUE THREAD

**Issue by 1138-4EB** [ghdl/ghdl#891]
As commented in gitter: [August 11, 2019 6:22 PM](https://gitter.im/ghdl1/Lobby?at=5d5040e3bfd2887f53cdf14c).

> [@wfjm]
> Is there a reason that release V0.36 is not mentioned in the NEWS.md file ?

> [@1138-4EB]
> @wfjm, releases 20181129 and v0.36-rc1 are also missing. We just forgot to update it. It was updated in the docs only. See:
>
>    - https://ghdl.readthedocs.io/en/latest/
>    - https://github.com/ghdl/ghdl/blob/master/doc/index.rst

**Comment by tgingold** [comment]
I am not sure we want to mention snapshots or release candidates.
