### ISSUE TITLE
Cannot find BASE-VER when building GHDL

### ISSUE THREAD

**Issue by dosadi** [ghdl/ghdl#932]
Description:  Trying to build GHDL snapshot from 10-21-2019, tried against GCC release 9.2:

$ ./configure --with-gcc=~/gcc --prefix=/opt/ghdl
Use full IEEE library
Build machine is: x86_64-linux-gnu
cannot find gcc/BASE-VER in ~/gcc

**Comment by tgingold** [comment]
Is the file present on your system ?

**Comment by dosadi** [comment]
Yes:

$ ls -l ~/gcc/gcc/BASE-VER
-rw-rw-r-- 1 jon jon 6 May  3 03:59 /home/jon/gcc/gcc/BASE-VER

**Comment by tgingold** [comment]
Ok.  You should try with $HOME/ instead of ~/
I am not sure that ~/ is expanded in the middle of a parameter.

**Comment by dosadi** [comment]
OK, thanks, that got me past that point.  Sorry about that....
