### ISSUE TITLE
Gate count?

### ISSUE THREAD

**Issue by rsc9421** [ghdl/ghdl#939]
Hi, there is a way to get the total gate count? 
best regards

**Comment by rsc9421** [comment]
The number of cells what means? I've understood that it represents a logic
gate

**Comment by 1138-4EB** [comment]
From https://en.wikipedia.org/wiki/Logic_block:

> a logic block or configurable logic block (CLB) is a fundamental building block of field-programmable gate array (FPGA) technology. Logic blocks can be configured by the engineer to provide reconfigurable logic gates. 

> In general, a logic block consists of a few logical cells (called ALM, LE, Slice etc.). A typical cell consists of a 4-input LUT, a Full adder (FA) and a D-type flip-flop

See also https://www.xilinx.com/support/documentation/application_notes/xapp059.pdf

**Comment by rsc9421** [comment]
Thanks, regards
