### ISSUE TITLE
No check.mcode target

### ISSUE THREAD

**Issue by yurivict** [ghdl/ghdl#988]
The code suggests that ```check``` is the target to test the code, but it fails:
```
gmake[1]: *** No rule to make target 'check.mcode', needed by 'check'.  Stop.
```
also
```
gmake[1]: *** No rule to make target 'check.llvm', needed by 'check'.  Stop.
```

**Comment by tgingold** [comment]
Ok, as you know the testsuite is within a subdir.
Should we simply remove the `check` target.
