### ISSUE TITLE
Build ignored the '-j NCPUs' option

### ISSUE THREAD

**Issue by yurivict** [ghdl/ghdl#989]
It always builds on one CPU, when normally projects should build on multiple CPUs.

**Comment by tgingold** [comment]
Yes, but `make` is not able to pass the `-j NCPU` option to a sub-builder (expected itself).
You can use: `make GNATMAKE="gnatmake -j4"`

**Comment by yurivict** [comment]
```MAKEFLAGS``` or ```MFLAGS``` contain ```-jN``` supplied to GNU make.

**Comment by 1138-4EB** [comment]
> `MAKEFLAGS` or `MFLAGS` contain `-jN` supplied to GNU make.

Those variables are passed to GNU make, but not to gnatmake, which is the (sub-builder) tool that does the heavy compilation work actually. The syntax suggested by @tgingold will ensure that `-jN` is passed to gnatmake. See:

https://github.com/ghdl/ghdl/blob/a08e8ce832701dd0832330e783009b20b34f6782/Makefile.in#L596-L603

**Comment by tgingold** [comment]
With gnu make, MAKEFLAGS does not contain -jN but parameters for the job server.

I fear there is no easy solutions.  Any proposal is welcome.
